/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtocolsRouteImport } from './routes/protocols'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ProtocolsRoute = ProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/consultation': typeof ConsultationRoute
  '/dashboard': typeof DashboardRoute
  '/protocols': typeof ProtocolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/consultation': typeof ConsultationRoute
  '/dashboard': typeof DashboardRoute
  '/protocols': typeof ProtocolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/consultation': typeof ConsultationRoute
  '/dashboard': typeof DashboardRoute
  '/protocols': typeof ProtocolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/consultation' | '/dashboard' | '/protocols'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/consultation' | '/dashboard' | '/protocols'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/consultation'
    | '/dashboard'
    | '/protocols'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConsultationRoute: typeof ConsultationRoute
  DashboardRoute: typeof DashboardRoute
  ProtocolsRoute: typeof ProtocolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/protocols': {
      id: '/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof ProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConsultationRoute: ConsultationRoute,
  DashboardRoute: DashboardRoute,
  ProtocolsRoute: ProtocolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
